FROM maven:3.6.3-jdk-11 AS compile
RUN git clone https://github.com/nicktodd/spring-course.git /usr/src/mymaven
WORKDIR /usr/src/mymaven/Solutions/workspace/CompactDiscDaoWithRestAndBoot
RUN mvn -Dmaven.test.skip=true package
#RUN ls /usr/src/mymaven/target

FROM openjdk:8
COPY --from=compile /usr/src/mymaven/Solutions/workspace/CompactDiscDaoWithRestAndBoot/target/CompactDiscRestDataBoot-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'echo spring.datasource.url=jdbc:mysql://mysql:3306/conygre > application.properties'
RUN sh -c 'echo spring.datasource.username=root >> application.properties'
RUN sh -c 'echo spring.datasource.password=c0nygre1 >> application.properties'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /app.jar" ]
